"""Add warehouse and transfer models

Revision ID: 0abf36205b5a
Revises: 845a55b97a35
Create Date: 2025-07-17 19:27:13.497958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abf36205b5a'
down_revision: Union[str, Sequence[str], None] = '845a55b97a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # table name changed
    # op.rename_table("suppliers", "warehouses")
    # op.alter_column("purchase_orders", "supplier_id", new_column_name="warehouse_id", existing_type=sa.UUID())
    # op.drop_constraint("purchase_orders_supplier_id_fkey", "purchase_orders", type_="foreignkey")
    # op.create_foreign_key("purchase_orders_warehouse_id_fkey", "purchase_orders", "warehouses", ["warehouse_id"], ["id"])

    op.drop_constraint('purchase_orders_supplier_id_fkey', 'purchase_orders', type_='foreignkey')
    op.drop_table('product_suppliers')
    op.drop_table('suppliers')
    op.alter_column("purchase_orders", "supplier_id", new_column_name="warehouse_id", existing_type=sa.UUID())
    

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('warehouse_transfers',
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('transfer_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    op.create_table('warehouse_transfer_items',
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('received_quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['warehouse_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key("purchase_orders_warehouse_id_fkey", "purchase_orders", "warehouses", ["warehouse_id"], ["id"])
    
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key('purchase_orders_supplier_id_fkey', 'purchase_orders', 'suppliers', ['supplier_id'], ['id'])
    op.create_table('suppliers',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='suppliers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_suppliers',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_price', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_order_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_preferred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_suppliers_product_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='product_suppliers_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_suppliers_pkey')
    )
    op.drop_table('warehouse_transfer_items')
    op.drop_table('warehouse_transfers')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
