"""Add created_at to warehouse_stock

Revision ID: 2aeb48dfb23b
Revises: 14492d90959a
Create Date: 2025-07-19 20:16:25.755429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aeb48dfb23b'
down_revision: Union[str, Sequence[str], None] = '14492d90959a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('Warehouse_id', sa.UUID(), nullable=False))
    op.drop_constraint('purchase_orders_warehouse_id_fkey', 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'warehouses', ['Warehouse_id'], ['id'])
    op.drop_column('purchase_orders', 'warehouse_id')
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    op.add_column('warehouse_stock', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_stock', 'created_at')
    op.alter_column('quotations', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('purchase_orders', sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key('purchase_orders_warehouse_id_fkey', 'purchase_orders', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('purchase_orders', 'Warehouse_id')
    # ### end Alembic commands ###
