from alembic import op
import sqlalchemy as sa

revision = '327254eee725'
down_revision = '02ac10e7921b'
branch_labels = None
depends_on = None

def upgrade():
    # 1. Add user_id as TEXT/nullable
    op.add_column('quotations', sa.Column('user_id', sa.Text(), nullable=True))

    # 2. Populate with a valid UUID string existing in users.id
    op.execute(
        "UPDATE quotations SET user_id = '361683cb-70bd-4f0c-b3f7-f71a90e8212f' WHERE user_id IS NULL"
    )

    # 3. Alter column type to UUID, casting from text
    op.execute(
        "ALTER TABLE quotations ALTER COLUMN user_id TYPE uuid USING user_id::uuid"
    )

    # 4. Make it non-nullable
    op.alter_column('quotations', 'user_id', nullable=False)

    # 5. Create foreign key constraint
    op.create_foreign_key(
        'fk_quotations_user_id_users',
        'quotations', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'
    )

def downgrade():
    op.drop_constraint('fk_quotations_user_id_users', 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'user_id')






# """Add user_id to quotations

# Revision ID: 327254eee725
# Revises: 02ac10e7921b
# Create Date: 2025-07-01 17:20:49.204884

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '327254eee725'
# down_revision: Union[str, Sequence[str], None] = '02ac10e7921b'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('quotations', sa.Column('user_id', sa.String(), nullable=False))
#     op.create_foreign_key(None, 'quotations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'quotations', type_='foreignkey')
#     op.drop_column('quotations', 'user_id')
#     # ### end Alembic commands ###
