"""Add unique constraint to notifications

Revision ID: 62fac8c8cf29
Revises: c5e1e777565a
Create Date: 2025-08-11 13:14:10.612742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fac8c8cf29'
down_revision: Union[str, Sequence[str], None] = 'c5e1e777565a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_type_ref_unread', 'notifications', ['user_id', 'type', 'reference_id', 'is_read'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint('uq_user_type_ref_unread', 'notifications', type_='unique')
    # ### end Alembic commands ###
