"""Add discount, tax, id to SaleItem

Revision ID: 7afe556ece2c
Revises: cc3c6f44f45d
Create Date: 2025-07-29 08:37:51.236207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7afe556ece2c'
down_revision: Union[str, Sequence[str], None] = 'cc3c6f44f45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    op.add_column('sale_items', sa.Column('discount', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('sale_items', sa.Column('tax', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.alter_column('sales', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'partial', 'paid', name='paymentstatusenum'),
               nullable=True,
               existing_server_default=sa.text("'unpaid'::paymentstatusenum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'partial', 'paid', name='paymentstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'unpaid'::paymentstatusenum"))
    op.drop_column('sale_items', 'tax')
    op.drop_column('sale_items', 'discount')
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
