"""Add Sale and SaleItem models

Revision ID: b2404a2e2fda
Revises: cd448867c385
Create Date: 2025-07-10 20:06:19.201650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2404a2e2fda'
down_revision: Union[str, Sequence[str], None] = 'cd448867c385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('sale_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_items',
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('line_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(), 
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_table('sale_items')
    op.drop_table('sales')
    # ### end Alembic commands ###
