"""Initial migration

Revision ID: d9f8802620c1
Revises: 6ce07287e79f
Create Date: 2025-07-03 08:04:21.120178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9f8802620c1'
down_revision: Union[str, Sequence[str], None] = '6ce07287e79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('business_license', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('services', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('project_value', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('media_data', sa.Text(), nullable=False),
    sa.Column('media_mimetype', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # ### end Alembic commands ###

    # (A) Drop the existing foreign key so we can change the column type
    op.drop_constraint(
        "fk_quotations_user_id_users",
        "quotations",
        type_="foreignkey"
    )
    # (B) Alter the user_id column type with proper casting
    op.execute(
        "ALTER TABLE quotations ALTER COLUMN user_id TYPE UUID USING user_id::uuid;"
    )
    # (C) Recreate the foreign key constraint with CASCADE
    op.create_foreign_key(
        "fk_quotations_user_id_users",
        "quotations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE"
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    op.drop_table('project_media')
    op.drop_table('projects')
    op.drop_table('contractor_profiles')
    # ### end Alembic commands ###

 # 1. Drop the foreign key constraint
    op.drop_constraint(
        "fk_quotations_user_id_users",
        "quotations",
        type_="foreignkey"
    )
    # 2. Revert user_id column back to VARCHAR with casting
    op.execute(
        "ALTER TABLE quotations ALTER COLUMN user_id TYPE VARCHAR USING user_id::text;"
    )
    # 3. Recreate the foreign key constraint
    op.create_foreign_key(
        "fk_quotations_user_id_users",
        "quotations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE"
    )
