"""Add Product and Supplier models

Revision ID: eb5630c7451a
Revises: 74f18878f08c
Create Date: 2025-07-08 18:39:37.117109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types

# revision identifiers, used by Alembic.
revision: str = 'eb5630c7451a'
down_revision: Union[str, Sequence[str], None] = '74f18878f08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('current_stock', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('min_stock_level', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('selling_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('contractor_profiles', 'website_url',
               existing_type=sa.VARCHAR(length=500),
               type_=app.core.types.HttpUrlType(length=2083),
               existing_nullable=True)
    # op.alter_column('quotations', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('contractor_profiles', 'website_url',
               existing_type=app.core.types.HttpUrlType(length=2083),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_table('suppliers')
    op.drop_table('products')
    # ### end Alembic commands ###
